In [1]:
import numpy as np
x = np.array([
    [10, 12, 14, 16, 18],
    [20, 22, 24, 26, 28],
    [30, 32, 34, 36, 38],
    [40, 42, 44, 46, 48]
])


In [11]:
# Q1. Array Creation and Properties
# Using the dataset x:
# 1.	Display the shape, size, and datatype of the array.
# 2.	Find the sum of all elements in the dataset.
print(np.shape(x))
print(type(x))
print(np.size(x))
print(np.sum(x))

(4, 5)
<class 'numpy.ndarray'>
20
580


In [15]:
# Q2. Even Value Extraction
# From the same dataset x:
# 1.	Create a 1-D NumPy array that contains only even values.
# 2.	Count the total number of even elements.
even_array = x[x%2==0]
print(even_array)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [17]:
count = len(even_array)
print(count)

20


In [26]:
# Q3. Indexing and Slicing
# Using the dataset x:
# 1.	Extract the third column.
# 2.	Extract the second row.
# 3.	Extract a sub-matrix consisting of rows 2–3 and columns 3–5.
print(x[:,2])
print(x[1,:])
sub_matrix = x[1:3, 2:5]
print(sub_matrix)


[14 24 34 44]
[20 22 24 26 28]
[[24 26 28]
 [34 36 38]]


In [29]:
x[x > 30] = -1
print(x)

[[10 12 14 16 18]
 [20 22 24 26 28]
 [30 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


In [31]:
x[3] = [1, 2, 3, 4, 5]
print(x)

[[10 12 14 16 18]
 [20 22 24 26 28]
 [30 -1 -1 -1 -1]
 [ 1  2  3  4  5]]


In [36]:
names = np.array(["Roxana", "Statira", "Roxana", "Statira", "Roxana"])
scores = np.array([126, 115, 130, 141, 132])
scores_less_130 = scores[scores < 130]
statira_scores = scores[names == "Statira"]
# 3.	Add 10 marks to Roxana’s scores only
#vectorized in-place operation
scores[names=="Roxana"]+=10
#vectorized in-place operation
print(scores)


[136 115 140 141 142]


In [37]:
import pandas as pd

data = {
    "Population": [1400000000, 331000000, 67000000, 83000000],
    "Capital": ["New Delhi", "Washington D.C.", "Paris", "Berlin"]
}

countries = ["India", "USA", "France", "Germany"]

df = pd.DataFrame(data, index=countries)

print(df)


         Population          Capital
India    1400000000        New Delhi
USA       331000000  Washington D.C.
France     67000000            Paris
Germany    83000000           Berlin


In [38]:


df = pd.DataFrame({
    "Population": [1400000000, 331000000, 67000000, 83000000],
    "Capital": ["New Delhi", "Washington D.C.", "Paris", "Berlin"]
}, index=["India", "USA", "France", "Germany"])


In [39]:
df.head()


,Population,Capital
India,1400000000,New Delhi
USA,331000000,Washington D.C.
France,67000000,Paris
Germany,83000000,Berlin


In [40]:
df.info()
df.dtypes


<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, India to Germany
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Population  4 non-null      int64 
 1   Capital     4 non-null      object
dtypes: int64(1), object(1)
memory usage: 96.0+ bytes


Population     int64
Capital       object
dtype: object

In [41]:
df.loc["India", "Population"]


np.int64(1400000000)

In [42]:
df[df["Population"] > 100000000]
df["GDP"] = [3.7, 25.4, 2.9, 4.2]  # example values
df.rename(columns={"Population": "Pop"}, inplace=True)
df.drop("Capital", axis=1, inplace=True)


In [43]:
df.sort_values("Pop")      # ascending
df.sort_values("Pop", ascending=False)  # descending
df["Pop"].mean()


np.float64(470250000.0)